networks:
  stream_processing_network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - stream_processing_network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - stream_processing_network

  kafka-producer-app:

    build:
      context: ./kafka-streams-app
      dockerfile: Dockerfile
    container_name: kafka-producer-app

    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CHALLENGER_API_URL: http://gc25-challenger:8866
    networks:
      - stream_processing_network
    volumes:
      - ../target:/app/kafka
    command: [ "java", "-jar", "/app/kafka/thermal-defect-kafka-1.0.jar", "producer" ]



  kafka-consumer-app:
    build: ./kafka-streams-app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_PARTITIONS: 2
    networks:
      - stream_processing_network
    volumes:
      - ../target:/app/kafka
      - ../Results:/app/Results
    command: [ "java", "-jar", "/app/kafka/thermal-defect-kafka-1.0.jar", "consumer" ]






