networks:
  stream_processing_network:
    driver: bridge
    name: stream_processing_network

services:
  ## FLINK - JOBMANAGER
  flink-jobmanager:
    build: ./flink/
    container_name: flink-jobmanager
    networks:
      - stream_processing_network
    tty: true
    volumes:
      - ../src:/opt/flink/src
      - ../Results:/Results
      - ../target:/opt/flink/usrlib
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager

  ## FLINK - TASKMANAGER
  flink-taskmanager:
    build: ./flink/
    networks:
      - stream_processing_network
    tty: true
    volumes:
      - ../src:/opt/flink/src
      - ../Results:/Results
      - ../target:/opt/flink/usrlib
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager